# Generated by Django 5.1 on 2024-12-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('UNIVERSAL', 'Універсальна'), ('DEBIT', 'Дебетова'), ('CREDIT', 'Кредитна'), ('SAVINGS', 'Ощадна')], max_length=16)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('pin', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('USD', 'Долар США'), ('EUR', 'Євро'), ('UAN', 'Гривня')], max_length=3)),
                ('registration_date', models.DateField()),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('itn', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.FloatField()),
                ('dept', models.FloatField(default=0)),
                ('interest_rate', models.FloatField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='paydesk.account')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='paydesk.account')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('TRANSFER', 'Переказ коштів'), ('CASH_WITHDRAWAL', 'Видача готівки'), ('RECHARGE', 'Поповнення рахунку'), ('CREDIT_PAYMENT', 'Оплата кредиту')], max_length=16)),
                ('operation_datetime', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('recipient_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_operations', to='paydesk.account')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_operations', to='paydesk.account')),
                ('recipient_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_operations', to='paydesk.person')),
                ('sender_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_operations', to='paydesk.person')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paydesk.person'),
        ),
    ]
